apiVersion: v1
kind: ConfigMap
metadata:
  name: scterm-server
data:
  application.properties: |-
    ibm.mq.connName=ibmmq(1414)

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: scterm-server-deployment
spec:
  selector:
    matchLabels:
      app: scterm-server
  replicas: 1
  template:
    metadata:
      labels:
        app: scterm-server
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8081"
        prometheus.io/scheme: "http"
        prometheus.io/path: "/actuator/prometheus"
    spec:
      containers:
        - name: scterm-server
          image: localhost.localdomain:5000/scterm-server:1.0-SNAPSHOT
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 7777
              name: iso

---

apiVersion: v1
kind: Service
metadata:
  name: scterm-server
spec:
  selector:
    app: scterm-server
  type: NodePort
  ports:
    - protocol: TCP
      name: iso
      port: 7777
      targetPort: 7777
      nodePort: 31777

---
